services:
  - type: web
    name: stock-material-erp-api
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
